"""Tests for the fallback PDF extractor and the page-locator path.

Run:  python3 -m unittest discover -s tests -v
No dependencies beyond the standard library — the PDFs are built here, byte by
byte, rather than shipped as binary fixtures or generated by a platform tool, so
these tests run identically on a colleague's machine.
"""
from __future__ import annotations

import re
import sys
import tempfile
import unittest
from unittest import mock
import zipfile
import os
import zlib
from io import BytesIO
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bridge.contract import IndexRequest, Message, Source  # noqa: E402
from bridge.extract import (  # noqa: E402
    PdfExtractionError,
    _poppler_path,
    extract_pdf_pages,
    extract_pdf_pages_with_engine,
)
from bridge.extract_office import (  # noqa: E402
    OfficeExtractionError, extract_office_units, office_kind,
)
from bridge.providers.builtin_retrieval import BuiltinRetrieval  # noqa: E402


def make_pdf(pages: list[str], encoding: str = "/WinAnsiEncoding",
             compress: bool = True) -> bytes:
    """Assemble a small but genuinely valid PDF, one content stream per page."""
    out = bytearray(b"%PDF-1.4\n")
    for i, text in enumerate(pages, start=1):
        body = f"BT /F1 12 Tf 72 720 Td ({text}) Tj ET".encode("cp1252", "replace")
        if compress:
            stream, filt = zlib.compress(body), b"/Filter /FlateDecode "
        else:
            stream, filt = body, b""
        out += (
            f"{i} 0 obj\n<< {filt.decode()}/Length {len(stream)} "
            f"/FontEncoding {encoding} >>\nstream\n".encode("ascii")
        )
        out += stream + b"\nendstream\nendobj\n"
    out += b"trailer\n<< /Root 1 0 R >>\n%%EOF\n"
    return bytes(out)


def make_pdf_cr_delimited(pages: list[str]) -> bytes:
    """A PDF that ends its lines with a bare CR, as PDF 1.7 §7.2.3 permits.

    Real files do this: the EUA report (checked 2026-08-27) writes
    `endstream\rendobj\r`, and every one of its 107 streams was invisible to a
    reader that assumed LF. Regression fixture for that file.
    """
    out = bytearray(b"%PDF-1.4\r")
    for i, text in enumerate(pages, start=1):
        body = f"BT /F1 12 Tf 72 720 Td ({text}) Tj ET".encode("cp1252", "replace")
        stream = zlib.compress(body)
        out += (
            f"{i} 0 obj\r<< /Filter /FlateDecode /Length {len(stream)} "
            f"/FontEncoding /WinAnsiEncoding >>\rstream\r\n".encode("ascii")
        )
        out += stream + b"\rendstream\rendobj\r"
    out += b"trailer\r<< /Root 1 0 R >>\r%%EOF\r"
    return bytes(out)


class TestPdfExtractorSelection(unittest.TestCase):
    """Poppler when the institution has it, stdlib when it does not.

    The same rule as `RETRIEVAL_PROVIDER=auto`: use what is already installed,
    ship a fallback anyway, and say which one ran. Poppler reads PDFs this
    module's fallback cannot — the EUA report measured 12% against pdftotext's
    100% (2026-08-27) — but requiring it would break the promise that the demo
    runs with nothing installed.
    """

    def test_reports_which_extractor_ran(self):
        pages, engine = extract_pdf_pages_with_engine(make_pdf(["Seite"]))
        self.assertIn(engine, ("poppler", "builtin"))
        self.assertTrue(any("Seite" in p for p in pages))

    def test_env_can_force_the_builtin_extractor(self):
        with mock.patch.dict(os.environ, {"PDF_EXTRACTOR": "builtin"}):
            _, engine = extract_pdf_pages_with_engine(make_pdf(["Seite"]))
        self.assertEqual(engine, "builtin")

    def test_falls_back_when_poppler_is_absent(self):
        with mock.patch.dict(os.environ, {"PDF_EXTRACTOR": "auto"}), \
             mock.patch("bridge.extract._poppler_path", return_value=None):
            pages, engine = extract_pdf_pages_with_engine(make_pdf(["Seite"]))
        self.assertEqual(engine, "builtin")
        self.assertTrue(any("Seite" in p for p in pages))

    def test_explicit_poppler_request_does_not_silently_downgrade(self):
        """Asked for explicitly but unusable: raise, do not quietly do worse.

        Mirrors the RETRIEVAL_PROVIDER=embeddings case, which warns rather than
        letting an operator believe they have retrieval they do not have. Here
        the difference is whole pages of text, so it raises.
        """
        with mock.patch.dict(os.environ, {"PDF_EXTRACTOR": "poppler"}), \
             mock.patch("bridge.extract._poppler_path", return_value=None):
            with self.assertRaises(PdfExtractionError) as ctx:
                extract_pdf_pages_with_engine(make_pdf(["Seite"]))
        self.assertIn("pdftotext", str(ctx.exception))

    def test_page_count_and_order_survive_either_engine(self):
        """A locator is only checkable if page N is page N in both engines."""
        pdf = make_pdf(["Alpha", "Beta", "Gamma"])
        builtin, _ = extract_pdf_pages_with_engine(pdf, engine="builtin")
        self.assertEqual(len(builtin), 3)
        self.assertIn("Alpha", builtin[0])
        self.assertIn("Gamma", builtin[2])
        # Not asserted against Poppler here: `make_pdf` writes content streams
        # without a page tree or xref, which this module's reader accepts and a
        # conforming parser rightly rejects. Poppler's page numbering is covered
        # by the real-PDF fixtures instead.

    def test_scanned_pdf_still_refuses_under_poppler(self):
        """Poppler returning nothing means scanned — still a refusal, not "".

        A scanned PDF that returns empty strings would be indexed as a document
        with no text, which is how a course silently loses a file.
        """
        if not _poppler_path():
            self.skipTest("poppler not installed")
        # Poppler reads a scan without complaint and returns blank pages, so
        # this is asserted on its *output*, not on a rejected file: an earlier
        # version of this test used a PDF poppler refused outright, which
        # passed while the real case — ocr_test.pdf, one empty page returned as
        # a valid document — went through silently.
        with mock.patch("bridge.extract.subprocess.run") as run:
            run.return_value = mock.Mock(returncode=0, stdout=b"\n\f\n\f", stderr=b"")
            with self.assertRaises(PdfExtractionError) as ctx:
                extract_pdf_pages_with_engine(make_pdf(["x"]), engine="poppler")
        self.assertIn("OCR", str(ctx.exception))


class TestPdfExtraction(unittest.TestCase):
    def test_extracts_text_from_a_real_pdf(self):
        pages = extract_pdf_pages(make_pdf(["Monaden sind Monoide."]))
        self.assertEqual(len(pages), 1)
        self.assertIn("Monaden", pages[0])

    def test_one_entry_per_page_in_order(self):
        pages = extract_pdf_pages(make_pdf(["Seite eins", "Seite zwei", "Seite drei"]))
        self.assertEqual(len(pages), 3)
        self.assertIn("eins", pages[0])
        self.assertIn("drei", pages[2])

    def test_reads_uncompressed_streams(self):
        pages = extract_pdf_pages(make_pdf(["Unkomprimiert"], compress=False))
        self.assertIn("Unkomprimiert", pages[0])

    def test_cr_delimited_pdf_is_not_mistaken_for_scanned(self):
        """A CR-delimited PDF must not be reported as scanned or encrypted.

        The failure this guards against is a wrong diagnosis, not a crash. The
        EUA report — 78k characters of text, 83 font objects, plainly not a
        scan — was refused with the scanned-or-encrypted message because every
        stream ended `\\rendstream` and the reader required `\\n`. Telling a
        reader their text document is a scan sends them to fix the wrong thing.
        """
        pages = extract_pdf_pages(make_pdf_cr_delimited(["Erste Seite", "Zweite Seite"]))
        self.assertTrue(any("Erste Seite" in p for p in pages), pages)
        self.assertTrue(any("Zweite Seite" in p for p in pages), pages)

    def test_rejects_non_pdf_rather_than_returning_junk(self):
        # An adapter must be able to tell "not a PDF" from "an empty PDF".
        with self.assertRaises(PdfExtractionError):
            extract_pdf_pages(b"PK\x03\x04 this is a docx")
        with self.assertRaises(PdfExtractionError):
            extract_pdf_pages(b"")

    def test_scanned_pdf_says_so_instead_of_pretending(self):
        # No text operators at all: the honest answer is an error naming OCR,
        # not silent success with zero content.
        scanned = b"%PDF-1.4\n1 0 obj\n<< /Subtype /Image /Length 4 >>\nstream\n" \
                  b"\x00\x01\x02\x03\nendstream\nendobj\ntrailer\n<< >>\n%%EOF\n"
        with self.assertRaises(PdfExtractionError) as ctx:
            extract_pdf_pages(scanned)
        self.assertIn("scanned", str(ctx.exception))


class TestGermanTextSurvives(unittest.TestCase):
    """Umlauts decide whether retrieval works on German lecture material.

    A mis-decoded "Größe" tokenises as a different word from the one a student
    types, so the passage is never retrieved — the failure is silent and looks
    like bad retrieval rather than bad decoding.
    """

    def test_winansi_umlauts(self):
        pages = extract_pdf_pages(make_pdf(["Übung: Größe und Maß"]))
        self.assertIn("Übung", pages[0])
        self.assertIn("Größe", pages[0])
        self.assertIn("Maß", pages[0])

    def test_declared_macroman_is_honoured(self):
        # macOS generators emit MacRoman and declare it; decoding it as cp1252
        # is the bug this guards. Build the bytes in MacRoman explicitly.
        body = "BT (Größe) Tj ET".encode("mac-roman")
        pdf = (b"%PDF-1.4\n1 0 obj\n<< /Encoding /MacRomanEncoding /Length "
               + str(len(body)).encode() + b" >>\nstream\n" + body
               + b"\nendstream\nendobj\ntrailer\n<< >>\n%%EOF\n")
        self.assertIn("Größe", extract_pdf_pages(pdf)[0])


class TestPageLocatorReachesCitations(unittest.TestCase):
    """The end-to-end reason the extractor is per page.

    `Source.locator` has been in the contract since the design, but until file
    extraction existed nothing ever populated it. A citation of "Vorlesung 3.pdf"
    alone cannot be checked; "Vorlesung 3.pdf, S. 12" can.
    """

    def setUp(self):
        self.tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        self.tmp.close()
        self.r = BuiltinRetrieval(self.tmp.name)

    def tearDown(self):
        Path(self.tmp.name).unlink(missing_ok=True)

    def test_locator_survives_index_and_retrieve(self):
        self.r.index(IndexRequest.from_dict({
            "course_ref": "studip:hpc",
            "documents": [
                {"activity_ref": "studip:hpc:file:9", "title": "Vorlesung 3.pdf",
                 "locator": "S. 12",
                 "text": "Ein Monad ist ein Monoid in der Kategorie der "
                         "Endofunktoren, sagt der Vorlesungsfoliensatz."},
            ],
        }))
        sources = self.r.retrieve("studip:hpc", "Was ist ein Monad?")
        self.assertTrue(sources)
        self.assertEqual(sources[0].title, "Vorlesung 3.pdf")
        self.assertEqual(sources[0].locator, "S. 12")

    def test_documents_without_a_locator_still_work(self):
        # Wiki pages and descriptions have no page number; the field must stay
        # optional rather than forcing adapters to invent one.
        self.r.index(IndexRequest.from_dict({
            "course_ref": "studip:x",
            "documents": [{"activity_ref": "studip:x:wiki:1", "title": "SLURM",
                           "text": "Jobs werden mit sbatch eingereicht."}],
        }))
        self.assertEqual(self.r.retrieve("studip:x", "sbatch")[0].locator, "")

class TestLoginPageIsNotAFile(unittest.TestCase):
    """Stud.IP's web front end answers an unauthenticated request with HTTP 200
    and a login page. A status-code check passes; only a content check catches it.

    The adapter uses the JSON-API download route, which does not have this
    problem — but a wrong base URL or a redirect lands on the web front end, and
    without this guard 23 KB of HTML reaches the PDF parser and gets reported as
    a corrupt file, sending whoever debugs it after the wrong problem.
    """

    def test_html_is_rejected_before_it_reaches_the_parser(self):
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "adapters"))
        import studip_adapter                                    # noqa: PLC0415

        login_page = b"<!DOCTYPE html>\n<html><body>Benutzername Passwort</body></html>"

        class FakeResponse:
            def read(self_inner):
                return login_page

            def __enter__(self_inner):
                return self_inner

            def __exit__(self_inner, *a):
                return False

        original = studip_adapter.urllib.request.urlopen
        studip_adapter.urllib.request.urlopen = lambda *a, **k: FakeResponse()
        studip_adapter.STUDIP_URL = "https://studip.example.org"
        studip_adapter.STUDIP_TOKEN = "t"
        try:
            with self.assertRaises(RuntimeError) as ctx:
                studip_adapter.studip_download("some-file-ref-id")
            self.assertIn("HTML page", str(ctx.exception))
        finally:
            studip_adapter.urllib.request.urlopen = original

    def test_a_real_pdf_still_passes(self):
        # The guard must not reject actual PDFs.
        self.assertTrue(make_pdf(["ok"]).startswith(b"%PDF"))

def make_pptx(slides: list[str], notes: dict[int, str] | None = None) -> bytes:
    """A minimal but structurally real .pptx: a ZIP of OOXML slide parts."""
    buf = BytesIO()
    ns = ('xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
          'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"')
    with zipfile.ZipFile(buf, "w") as z:
        for i, text in enumerate(slides, 1):
            z.writestr(f"ppt/slides/slide{i}.xml",
                       f'<?xml version="1.0"?><p:sld {ns}><p:cSld><p:spTree>'
                       f"<a:p><a:r><a:t>{text}</a:t></a:r></a:p>"
                       "</p:spTree></p:cSld></p:sld>")
        for i, text in (notes or {}).items():
            z.writestr(f"ppt/notesSlides/notesSlide{i}.xml",
                       f'<?xml version="1.0"?><p:notes {ns}>'
                       f"<a:p><a:r><a:t>{text}</a:t></a:r></a:p></p:notes>")
    return buf.getvalue()


def make_odp(pages: list[str]) -> bytes:
    """A minimal but structurally real .odp: ODF declares itself in `mimetype`."""
    buf = BytesIO()
    ns = ('xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" '
          'xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" '
          'xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0"')
    body = "".join(f"<draw:page><text:p>{t}</text:p></draw:page>" for t in pages)
    with zipfile.ZipFile(buf, "w") as z:
        z.writestr("mimetype", "application/vnd.oasis.opendocument.presentation")
        z.writestr("content.xml",
                   f'<?xml version="1.0"?><office:document-content {ns}>'
                   f"<office:body><office:presentation>{body}"
                   "</office:presentation></office:body></office:document-content>")
    return buf.getvalue()


class TestOfficeExtraction(unittest.TestCase):
    """Slides are where lecture content actually lives.

    Of the twelve files on the course this was built against, three are
    presentations or spreadsheets — a PDF-only extractor sees none of them.
    """

    def test_pptx_one_unit_per_slide_in_order(self):
        units = extract_office_units(make_pptx(["Erste Folie", "Zweite Folie",
                                                "Dritte Folie"]))
        self.assertEqual([loc for loc, _ in units],
                         ["Folie 1", "Folie 2", "Folie 3"])
        self.assertIn("Dritte", units[2][1])

    def test_pptx_includes_speaker_notes(self):
        # A slide often carries three words while the substance is in the notes.
        units = extract_office_units(
            make_pptx(["Titel"], notes={1: "Hier steht die eigentliche Erklärung"}))
        self.assertIn("eigentliche Erklärung", units[0][1])

    def test_odp_is_handled_too(self):
        # A German university course has LibreOffice files alongside Microsoft
        # ones — the course this was built against has a .odp next to a .pptx.
        units = extract_office_units(make_odp(["Folie eins", "Folie zwei"]))
        self.assertEqual(len(units), 2)
        self.assertIn("eins", units[0][1])

    def test_umlauts_survive(self):
        units = extract_office_units(make_pptx(["Größe, Maß und Übung"]))
        self.assertIn("Größe", units[0][1])
        self.assertIn("Maß", units[0][1])

    def test_kind_detection_is_by_content_not_name(self):
        # Stud.IP truncated MIME types on the real course listing, so sniffing
        # the bytes is what actually decides.
        self.assertEqual(office_kind(make_pptx(["x"])), "pptx")
        self.assertEqual(office_kind(make_odp(["x"])), "odp")
        self.assertEqual(office_kind(b"%PDF-1.4 not a zip"), "")

    def test_legacy_binary_formats_say_why(self):
        # .doc/.ppt/.xls are OLE compound files, not ZIPs — a different problem.
        ole = b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1" + b"\x00" * 32
        with self.assertRaises(OfficeExtractionError) as ctx:
            extract_office_units(ole)
        self.assertIn("legacy", str(ctx.exception))

    def test_image_only_deck_points_at_vision(self):
        # An honest dead end: say it needs a vision model, do not return "".
        with self.assertRaises(OfficeExtractionError) as ctx:
            extract_office_units(make_pptx(["", ""]))
        self.assertIn("vision", str(ctx.exception))

    def test_a_pdf_is_not_mistaken_for_office(self):
        self.assertEqual(office_kind(make_pdf(["text"])), "")


class TestUngroundedRefusal(unittest.TestCase):
    """A course was named but retrieval found nothing: the model must refuse.

    Found live, not in review: asked "Wie reiche ich einen Job ein?" against an
    HPC course whose passages did not match ("job" vs "jobskript" — the lexical
    provider has no stemming), gpt-oss-120b answered from general knowledge with
    a confident guide to applying for jobs on LinkedIn. Nothing in the response
    marked it as ungrounded.

    That is the exact failure grounding exists to prevent, so the refusal is
    instructed explicitly rather than left to the model.
    """

    def test_no_context_but_grounded_gets_the_refusal_instruction(self):
        from bridge.providers.openai_chat import (      # noqa: PLC0415
            SYSTEM_NO_CONTEXT, OpenAICompatibleChat,
        )
        wire = OpenAICompatibleChat(
            base_url="http://x", model="m")._payload(
                [Message(role="user", content="Wie reiche ich einen Job ein?")],
                None, grounded=True)
        self.assertEqual(wire[0]["content"], SYSTEM_NO_CONTEXT)

    def test_open_chat_without_a_course_is_left_alone(self):
        # No course named is ordinary open chat — not a refusal case.
        from bridge.providers.openai_chat import OpenAICompatibleChat  # noqa: PLC0415
        wire = OpenAICompatibleChat(
            base_url="http://x", model="m")._payload(
                [Message(role="user", content="Was ist ein Monad?")],
                None, grounded=False)
        self.assertEqual(len(wire), 1)
        self.assertEqual(wire[0]["role"], "user")

    def test_context_present_uses_the_grounded_prompt(self):
        from bridge.providers.openai_chat import (      # noqa: PLC0415
            SYSTEM_GROUNDED, OpenAICompatibleChat,
        )
        ctx = [(Source(title="V3.pdf", locator="S. 12"), "Ein Jobskript ...")]
        wire = OpenAICompatibleChat(
            base_url="http://x", model="m")._payload(
                [Message(role="user", content="Wie?")], ctx, grounded=True)
        self.assertEqual(wire[0]["content"], SYSTEM_GROUNDED)
        self.assertIn("S. 12", wire[1]["content"])


class TestGermanCompoundRetrieval(unittest.TestCase):
    """German glues words together; lexical matching does not.

    Found on a live course: "Was kam bei der Lehrendenbefragung heraus?"
    returned nothing at all from a course containing
    `SOUVER@N Lehrendenbefragung.pdf` with 38 indexed pages, because a page
    saying "Befragung der Lehrenden" shares no token with the compound.
    """

    def setUp(self):
        from bridge.providers.builtin_retrieval import BuiltinRetrieval  # noqa: PLC0415
        self.tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        self.tmp.close()
        self.r = BuiltinRetrieval(self.tmp.name)
        self.r.index(IndexRequest.from_dict({
            "course_ref": "studip:w",
            "documents": [
                {"activity_ref": "a", "title": "Lehrendenbefragung.pdf",
                 "locator": "S. 3",
                 "text": "Die Befragung der Lehrenden ergab, dass digitale "
                         "Werkzeuge überwiegend positiv bewertet werden."},
                {"activity_ref": "b", "title": "Handout.pdf", "locator": "S. 112",
                 "text": "Allgemeine Erfahrungen aus der Beratung von "
                         "Studierenden im Servicebereich der Universität."},
            ],
        }))

    def tearDown(self):
        Path(self.tmp.name).unlink(missing_ok=True)

    def test_compound_query_finds_the_spelled_out_document(self):
        hits = self.r.retrieve("studip:w", "Was kam bei der Lehrendenbefragung heraus?")
        self.assertTrue(hits, "compound query found nothing")
        self.assertEqual(hits[0].title, "Lehrendenbefragung.pdf")

    def test_plural_and_singular_collide(self):
        from bridge.providers.builtin_retrieval import tokenize  # noqa: PLC0415
        self.assertIn("klausur", tokenize("E-Klausuren"))
        self.assertIn("kompetenz", tokenize("KI-Kompetenzen"))

    def test_a_single_common_word_does_not_count_as_a_hit(self):
        # The relevance floor. Without it an unanswerable question still returns
        # passages, the model refuses, and the UI prints sources beneath the
        # refusal — which reads as a broken system.
        #
        # "Common" is relative to the course, so the corpus has to be big enough
        # for the word to actually be common: a term appearing in one chunk of
        # two is rare by any measure, and should still match.
        from bridge.providers.builtin_retrieval import BuiltinRetrieval  # noqa: PLC0415
        tmp = tempfile.NamedTemporaryFile(suffix=".json", delete=False)
        tmp.close()
        try:
            r = BuiltinRetrieval(tmp.name)
            r.index(IndexRequest.from_dict({
                "course_ref": "studip:big",
                "documents": [
                    {"activity_ref": f"h{i}", "title": "Handout.pdf",
                     "locator": f"S. {i}",
                     "text": f"Erfahrungen aus der Beratung, Abschnitt {i}. "
                             f"Hinweise zum Servicebereich der Universität."}
                    for i in range(1, 13)
                ],
            }))
            hits = r.retrieve("studip:big",
                              "Welche Erfahrungen gibt es mit Segelbooten?")
            self.assertEqual(hits, [],
                             "matched on the single common word 'Erfahrungen'")
        finally:
            Path(tmp.name).unlink(missing_ok=True)


class TestOnlyCitedSourcesAreReturned(unittest.TestCase):
    """Retrieval can return a topical page that does not answer the question.

    Live example: asked about experiences with E-Klausuren, a 168-page handout
    mentioning "OpenBooks-Klausuren" is a *correct* lexical hit and a useless
    citation. The model says the material does not answer the question — and
    listing four sources under that refusal makes a sound judgement read as a
    broken system. So the bridge returns only what the answer cited.
    """

    def setUp(self):
        sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
        from bridge.server import _keep_cited_sources       # noqa: PLC0415
        self.filter = _keep_cited_sources
        self.sources = [Source(title=f"D{i}.pdf", locator=f"S. {i}")
                        for i in range(1, 5)]

    def test_refusal_returns_no_sources(self):
        answer = "Die bereitgestellten Auszüge enthalten keine Angaben dazu."
        _, kept = self.filter(answer, self.sources)
        self.assertEqual(kept, [])

    def test_only_the_cited_subset_is_returned(self):
        _, kept = self.filter("Es gilt X [2] und ergänzend Y [4].", self.sources)
        self.assertEqual([s.title for s in kept], ["D2.pdf", "D4.pdf"])

    def test_fullwidth_brackets_count_as_citations(self):
        # gpt-oss-120b emitted 【1】 and 【2】 on a live run; matching only ASCII
        # brackets threw away every source of a well-grounded answer.
        answer, kept = self.filter("Definition【1】 und Kontext【2】.", self.sources)
        self.assertEqual([s.title for s in kept], ["D1.pdf", "D2.pdf"])
        self.assertIn("[1]", answer)

    def test_survivors_are_renumbered_to_match_the_list(self):
        # Citing only the fourth hit would otherwise print an answer referring
        # to [4] above a one-entry list labelled [4], with no [1]-[3] at all.
        answer, kept = self.filter("Der Vortrag [4] sagt X.", self.sources)
        self.assertEqual([s.title for s in kept], ["D4.pdf"])
        self.assertIn("[1]", answer)
        self.assertNotIn("[4]", answer)

    def test_out_of_range_citations_are_ignored(self):
        _, kept = self.filter("Siehe [9].", self.sources)
        self.assertEqual(kept, [])


if __name__ == "__main__":
    unittest.main()
